export const FETCH_INCOMPLETE_TRANSACTIONS_PROCESS = 'FETCH_INCOMPLETE_TRANSACTIONS_PROCESS';
export const FETCH_TRANSACTION_DETAILS_PROCESS = 'FETCH_TRANSACTION_DETAILS_PROCESS';
export const FETCH_AND_VERIFY_FILE_DETAILS_PROCESS = 'FETCH_AND_VERIFY_FILE_DETAILS_PROCESS';

export const FETCH_INCOMPLETE_TRANSACTIONS_QUEUE = 'fetch-incomplete-transaction-queue';
export const FETCH_TRANSACTION_DETAILS_QUEUE = 'fetch-transaction-details-queue';
export const VERIFY_AND_ADD_FILE_QUEUE = 'verify-and-add-file-queue';
